### ISSUE TITLE
Drive add-on occasionally fail to connect to the device, 

### ISSUE THREAD

**Issue by cary-rowen** [school510587/MetecBD-driver#1]
As stated in the title, Drive add-on occasionally fail to connect to the device, The user must restart or log off the computer to reconnect.
By looking at the log, I found:    raise RuntimeError( No MetecBD found".

This problem mostly occurs when the device is not properly removed.
I will upload the complete log:
[log.txt](https://github.com/school510587/MetecBD-driver/files/6451592/log.txt)

**Comment by school510587** [comment]
Hi,

This error occurred because of failed execution of the line (addon\brailleDisplayDrivers\MetecBD.py):

self._BrdDeviceNr = c_int(MetecBD.BrdInitDevice(c_int(0),byref(self._BrdDeviceTyp)))

That is, C function BrdInitDevice in MetecBD.dll has failed. I don't have source code of MetecBD.dll, so I cannot figure out any solution.

In fact, I also use 晴光中英文盲用資訊系統, an old screen reader that depends on MetecBD. This problem also happens frequently when I use it, so I think the key to solve the problem is inside the installed driver, and nothing can be done in NVDA itself or any addon.     在 2021年5月10日 星期一 下午07:11:05 [GMT+8]， ***@***.***> 寫道：  
 
 


As stated in the title, Drive add-on occasionally fail to connect to the device, The user must restart or log off the computer to reconnect.
By looking at the log, I found: raise RuntimeError( No MetecBD found".

This problem mostly occurs when the device is not properly removed.
I will upload the complete log:
log.txt

**Comment by cary-rowen** [comment]
This seems to be the case. I switched the Disable/Enable state of Metec-BD in the device manager to occasionally solve it.
Thanks.
